src/Entity/Message.php
<?php 

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

   
    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'sentMessages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user_message = null;

 
    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'receivedMessages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $receiver = null;

    #[ORM\Column(length: 255)]
    private ?string $message = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserMessage(): ?User
    {
        return $this->user_message;
    }

    public function setUserMessage(?User $user_message): static
    {
        $this->user_message = $user_message;
        return $this;
    }

    public function getReceiver(): ?User
    {
        return $this->receiver;
    }

    public function setReceiver(?User $receiver): static
    {
        $this->receiver = $receiver;
        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }
}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Message;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('message', TextareaType::class, [
                'label' => false,
                'attr' => [
                    'placeholder' => "écrire un message",
                    'class' => 'w-full p-4 bg-[#21213B] text-white text-[14px] placeholder:text-[14px] rounded-t-xl rounded-b-xl resize-none',
                    'rows' => 2,
                ]
            ])

            ->add('receiver', EntityType::class, [
                'class' => User::class,
                'label' => false,
                'attr' => [
                    "hidden" => "hidden"
                ]
            ])
            ->add('envoyer', SubmitType::class, [
                'attr' => [
                    "class" => "mt-2 w-20 bg-[#FF1B1C] opacity-75 hover:opacity-100 text-white text-[12px] text-center py-1 rounded-full"
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Message;
use App\Form\MessageType;
use App\Repository\MessageRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Doctrine\ORM\EntityManagerInterface;


final class MessageController extends AbstractController
{
    #[Route('/messages', name: 'messages')]
    public function messages(MessageRepository $messageRepository): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        $users = $messageRepository->findConversationUsers($user);

        return $this->render('message/index.html.twig', [
            'users' => $users,
        ]);
    }

    #[Route('/conversation/{userId}', name: 'conversation')]
    public function conversation(Request $request, EntityManagerInterface $em, UserRepository $userRepository, int $userId): Response
    {


        $userConnect = $this->getUser();
 /** @var \App\Entity\User $user */
        $receiver = $userRepository->find($userId);

        if (!$receiver) {
            throw $this->createNotFoundException("L'utilisateur demandé n'existe pas.");
        }
     
        $message = new Message;
        $form = $this->createForm(MessageType::class, $message);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $message->setUserMessage($userConnect);
            $message->setReceiver($receiver);


            $em->persist($message);
            $em->flush();

            $this->addFlash("message", "Message envoyé avec succès.");
            return $this->redirectToRoute("conversation", ['userId' => $userId]);
        }
        
        $messages = $em->getRepository(Message::class)->getConversation($userConnect, $receiver);

        return $this->render('message/conversation.html.twig', [
            'form' => $form->createView(),
            'messages' => $messages,
            
        ]);
    }
}

templates/message/conversation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MessageController!
{% endblock %}

{% block body %}
	<div class="mb-6 flex svg-post sticky top-0 bg-[#1E1E3F] z-10 p-4">
		<a href="{{ path('messages') }}">
			<svg class="svg-post" xmlns="http://www.w3.org/2000/svg" height="32" width="28" viewbox="0 0 448 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path fill="#e0e0e0" d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
		</a>
		<h1 class="w-100 text-center pt-1">Conversation</h1>
	</div>
	<div class="flex flex-col h-[70vh] overflow-y-auto" id="conversation">
		{% for message in messages %}
			<div class="mt-4 pl-4 mr-6 flex flex-col justify-center items-start bg-[#2A2A4F] rounded-r-2xl rounded-tl-2xl">
				<h2 class="border-b-2 border-b-[#E0E0E0]">{{ message.userMessage.username }}</h2>
				<p class="pt-2 pb-2">{{ message.message }}</p>
				<p>Destinataire :
					{{ message.receiver.username }}</p>
				<p>{{ message.createdAt|date('d/m/Y H:i') }}</p>
			</div>

		{% endfor %}
	</div>

	<div id="bottom"></div>
</div>
<div class="sticky bottom-0 bg-[#1E1E3F] w-full p-4">
	{{ form(form) }}
	</div>


	<script>

		function bottom() {
const conversation = document.getElementById('conversation');
if (conversation) {
conversation.scrollTop = conversation.scrollHeight;
}

}

document.addEventListener("DOMContentLoaded", function () {
bottom();
})

const form = document.querySelector("form");
if (form) {
form.addEventListener("submit", function () {
setTimeout(bottom, 200)
})
}
	</script>
{% endblock %}

templates/message/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MessageController!
{% endblock %}

{% block body %}
	<div class="mb-6 flex svg-post">
		<a href="{{ path('home') }}">
			<svg class="svg-post" xmlns="http://www.w3.org/2000/svg" height="32" width="28" viewbox="0 0 448 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path fill="#e0e0e0" d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
		</a>
		<h1 class="w-100 text-center pt-1">Messages</h1>
	</div>

	{% for user in users %}
		{% if app.user and user.userMessage == app.user %}
			{% else %}
				<div class="m-4 flex flex-col justify-center items-center color-post rounded-full">
						<a href="{{ path('conversation', {userId: user.id}) }}" class="userMessage-color flex flex-col justify-center items-center color-post">
							<h2 class="border-b-2 border-b-[#E0E0E0]">Utilisateur :
								{{ user.userMessage }}</h2>
							<p>{{ user.message }}</p>
							<p>Date :
								{{ user.createdAt|date }}</p>
						</a>
					</div>
				{% endif %}
		{% endfor %}

	{% endblock %}

templates/message/received.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MessageController!{% endblock %}

{% block body %}
<h1>Boite de reception</h1>
<p>Résumé de la messagerie</p>
<p>Vous avez reçus : {{ app.user.receivedMessages|length }} messages</p>
<p>Envoyés : {{ app.user.sentMessages|length }}</p>

<div>De</div>
<div>Sujet</div>
<div>Date</div>
<div>Actions</div>

 {% for message in app.user.receivedMessages %}
<div>{{ message.userMessage.username }}</div>
<div>{{ message.message }}</div>
<div>{{ message.createdAt|date }}</div>
{% endfor %}

{% endblock %}

templates/message/send.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conversation{% endblock %}

{% block body %}
<h1>Envoyer un message</h1>
{{ form(form) }}

{% endblock %}